import re

zh_tw = '''
        'title.dashboard': 'GenAI 總控制台 (Chief Control Plane)',
        'hero.eyebrow': 'GenAI 維運管理',
        'hero.title': '總控制台',
        'hero.sub': '單一儀表板管理執行、檢查警報、調整佇列優先級，並稽核生產歷史紀錄。',

        'label.auto_refresh': '自動重新整理',
        'label.language': '語言',
        'kpi.system_state': '系統狀態',
        'kpi.queue_depth': '排隊深度',
        'kpi.success_rate': '成功率',
        'kpi.avg_duration': '平均時長',
        'kpi.gpu_cost': '預估 GPU 成本',

        'tab.overview': '總覽 (Overview)',
        'tab.ops': '維運 (Operations)',
        'tab.detail': '執行細節',
        'tab.modules': '專案資產調整 (Workbench)',

        'overview.composer.title': '執行排程器',
        'overview.composer.sub': '產品模式支援依照優先級與版本化的設定檔進行佇列。',
        'overview.telemetry.title': '每日遙測報告',

        'ops.queue.title': '目前的佇列',
        'ops.alert.title': '系統警報',
        'ops.capacity.title': '容量與使用量',
        'ops.config.title': '執行設定檔版本',
        'ops.logs.title': '系統記錄',
        'ops.recent.title': '最近的執行',

        'detail.selector.title': '執行選擇器',
        'detail.summary.title': '執行摘要',
        'detail.timeline.title': '作業時間軸',
        'detail.related_alerts.title': '相關警報',
        'detail.logs.title': '執行記錄',

        'module.jobs.title': '背景作業佇列',
        'module.job_detail.title': '作業詳情',
        'module.job_events.title': '作業事件戳記',
        'module.job_logs.title': '即時日誌追蹤',
        'module.workbenches.title': '功能工作臺',
        'module.workbenches.sub': '可單獨執行文字、圖像、翻譯與語音，而無需執行完整流程。',
        'module.tab.story': '文本工作室',
        'module.tab.image': '圖像工作室',
        'module.tab.translation': '翻譯工作室',
        'module.tab.voice': '語音工作室',

        'image.live_preview.title': '即時預覽',
        'image.hint': '（此處顯示最新生成的圖像）',
        'image.selected': '已選圖像',
        'image.positive': '正向提示詞',
        'image.negative': '反向提示詞',

        'btn.refresh_now': '立即重新整理',
        'btn.start': '開始',
        'btn.stop': '停止',
        'btn.save_local': '儲存至本機',
        'btn.load_local': '從本機載入',
        'btn.save_version': '儲存為版本',
        'btn.record_start': '開始錄音',
        'btn.record_stop': '停止錄音',
        'btn.record_save': '儲存錄音',
        'btn.clear': '清除',
        'btn.refresh_detail': '重新整理詳情',
        'btn.refresh_jobs': '重新整理作業',
        'btn.stop_selected': '停止所選',
        'btn.refresh_images': '重新整理圖像',
        'btn.regen_selected': '重新生成所選',
        'btn.queue_image_module': '加入圖像佇列',
        'btn.regen_with_edits': '修改後重新生成',
        'btn.run_text_module': '執行文本作業',
        'btn.run_translation_module': '執行翻譯作業',
        'btn.run_voice_module': '執行語音作業',

        'th.job': '作業',
        'th.state': '狀態',
        'th.priority': '優先級',
        'th.books': '繪本數',
        'th.category': '類別',
        'th.age': '年齡',
        'th.action': '操作',
        'th.version': '版本',
        'th.created': '建立時間',
        'th.note': '備註',
        'th.usage': '用量',
        'th.run': '執行',
        'th.started': '開始時間',
        'th.duration': '時長',
        'th.result': '結果',
        'th.config': '設定',
        'th.type': '類型',
        'th.status': '狀態',
        'th.story_root': '故事根目錄',

        'msg.request_failed': '請求失敗，請檢查主控台。',
        'msg.refresh_failed': '重新整理失敗',
        'msg.select_module_job_first': '請先選擇一個作業。',
        'msg.no_module_jobs': '佇列中沒有作業。',
        'msg.no_module_job_selected': '沒有選中作業。',
        'msg.no_events': '沒有事件紀錄。',
        'msg.no_module_logs': '沒有日誌紀錄。',
        'msg.submitting_module_job': '正在提交作業...',
        'msg.module_job_queued': '作業已加入佇列！',
        'msg.failed_run_module_job': '作業提交失敗，請檢查主控台。',
        'msg.stop_requested_for_module_job': '已請求停止該作業！',
        'msg.failed_stop_module_job': '停止作業失敗。',
        'msg.none_selected': '未選取。',
        'msg.no_generated_images': '沒有找到已生成的圖像。',
        'msg.select_at_least_one_image': '請至少選擇一張圖像。',
        'msg.regenerating_selected_images': '正在重新生成選取的圖像...',
        'msg.regenerated_images': '成功送出重新生成請求！',
        'msg.failed_regenerate_selected_images': '重新生成失敗。',
        'msg.select_image_for_regen': '請選擇一個圖像與輸入提示詞。',
        'msg.regenerating_image_with_edits': '正在以新的設定重新生成...',
        'msg.image_regenerated_successfully': '成功送出重新生成請求！',
        'msg.image_regeneration_failed': '重新生成失敗。',
        'msg.failed_regenerate_image': '重新生成送出失敗。',
        'msg.recording_read_script': '請念出這段文字...',
        'msg.microphone_access_failed': '麥克風存取失敗。請檢查權限。',
        'msg.recording_captured': '已擷取錄音。',
        'msg.no_recording_available': '沒有可用的錄音。',
        'msg.speaker_sample_saved': '已儲存講者樣本檔案。',
        'msg.failed_save_recording': '儲存錄音失敗。',
        'msg.saved_local_profile': '已儲存本機設定檔。',
        'msg.preset_applied': '已套用預設值。',
        'msg.no_run_history': '沒有執行歷史紀錄。',
        'msg.no_runs_available': '目前沒有可用的執行。',
        'msg.queue_empty': '佇列目前為空。',
        'msg.no_alerts': '目前系統正常，無警報。',
        'msg.no_trend_data': '沒有足夠的趨勢資料可顯示。',
        'msg.no_saved_versions': '沒有已儲存的配置版本。',
        'msg.no_related_alerts': '在此次執行中沒有發現相關警報。',
        'msg.no_run_logs': '目前此執行沒有紀錄。',
        'msg.book_count_min': '本數 (最低上限數量)。',
        'msg.submitting_run_request': '正在提交執行請求...',
        'msg.run_started': '執行已開始！',
        'msg.run_queued': '執行已加入佇列。',
        'msg.failed_start_run': '執行請求失敗，請檢查主控台。',
        'msg.stopping_active_run': '正在停止執行...',
        'msg.stopped_and_started_next': '已停止執行並開始下一個作業。',
        'msg.stopped': '已停止執行。',
        'msg.failed_stop_run': '停止執行失敗。',
        'msg.saved_config_version': '已儲存設定版本！',
        'msg.failed_save_config_version': '儲存設定版本失敗。',
        'msg.applied_config_version': '已套用設定版本！',
        'msg.failed_apply_config_version': '套用設定版本失敗。',
        'msg.updated_priority': '已更新優先順序！',
        'msg.failed_reprioritize_job': '更新優先順序失敗。',
        'msg.canceled_job': '已取消作業！',
        'msg.failed_cancel_job': '取消作業失敗。',
        'msg.failed_ack_alert': '確認警報失敗。',
        'msg.loaded_local_profile': '已載入本機設定。',

        'meta.book': '第 %d 本',
        'meta.stage': '階段',
        'meta.updated': '更新時間',

        'state.idle': '閒置 (Idle)',
        'state.running': '執行中 (Running)',
        'state.completed': '已完成 (Completed)',
        'state.failed': '失敗 (Failed)',
        'state.stopped': '已停止 (Stopped)',
        'state.queued': '排隊中 (Queued)',
        'state.error': '錯誤 (Error)',
        'state.active': '作動中 (Active)',

        'placeholder.theme': '例如：恐龍、太空...',
        'placeholder.subcategory': '例如：友誼、勇敢...',
        'placeholder.seed': '隨機種子...',
        'placeholder.story_prompt': '在這裡輸入完整的故事提示詞...',
        'placeholder.story_materials': '（選填）提供角色的背景設定、特殊稱呼等資料。',
        'placeholder.story_prompt_preset': '若套用預設值，此處留空即可。',
        'placeholder.story_materials_preset': '若套用預設值，此處留空即可。',
        'placeholder.story_prompt_custom': '【自訂模式】請輸入詳細的提示詞，不會再合併預設知識。',
        'placeholder.story_materials_custom': '【自訂模式】請提供角色參考及其他附加訊息。',

        'option.story_input_mode.preset': '知識圖譜預設模式 (由系統生成)',
        'option.story_input_mode.custom': '自訂提示詞模式 (Custom Prompt)',
        'option.module_story_input_mode.preset': '知識圖譜預設模式 (由系統生成)',
        'option.module_story_input_mode.custom': '自訂提示詞模式 (Custom)',
        
        // Custom keys I added
        'label.tab_gallery': '歷史作品庫 (Gallery)',
        'nav.overview': '總覽 (Generate)',
        'nav.modules': '專案資產調整 (Workbench & Tools)'
'''

with open('pipeline/templates/dashboard.html', 'r', encoding='utf-8') as f:
    text = f.read()

# Replace the zh-TW dictionary
text = re.sub(r"'zh-TW': \{.*?(?='en': \{)", f"'zh-TW': {{\n{zh_tw}\n      }},\n      ", text, flags=re.DOTALL)

# Let's also enforce English default fallback just in case testing is requested
text = text.replace("'nav.ops': 'Operations',", "") # remove the hack from earlier
text = text.replace("'nav.ops': '維運 (Operations)',", "")

with open('pipeline/templates/dashboard.html', 'w', encoding='utf-8') as f:
    f.write(text)

print("Updated text!")
